# Generated by Django 5.1 on 2024-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speech_Therapist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hospital_name", models.CharField(max_length=28)),
                ("is_deleted", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
