# Generated by Django 5.1.1 on 2024-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_therapist', '0002_remove_speech_therapist_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech_therapist',
            name='phone_number',
            field=models.CharField(default='0741817334', max_length=28),
            preserve_default=False,
        ),
    ]
