# Generated by Django 5.1.1 on 2024-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_therapist', '0003_speech_therapist_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech_therapist',
            name='profile_picture',
            field=models.ImageField(default='/home/student/Pictures/userName.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech_therapist',
            name='role',
            field=models.CharField(default='speech therapist', max_length=28),
            preserve_default=False,
        ),
    ]
