# Generated by Django 5.1 on 2024-09-09 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_therapist', '0004_speech_therapist_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech_therapist',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='speech_therapist',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='speech_therapist',
            name='role',
        ),
        migrations.AddField(
            model_name='speech_therapist',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
