# Generated by Django 5.1 on 2024-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_therapist', '0005_remove_speech_therapist_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech_therapist',
            name='phone_number',
            field=models.CharField(default='0741817334', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech_therapist',
            name='profile_picture',
            field=models.ImageField(default='/home/student/Pictures/userName.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech_therapist',
            name='role',
            field=models.CharField(default='Therapist', max_length=28),
            preserve_default=False,
        ),
    ]
