# Generated by Django 5.1 on 2024-09-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_start_time', models.TimeField()),
                ('session_end_time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
