# Generated by Django 5.1 on 2024-09-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LevelOfStuttering",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type_of_stuttering", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
