# Generated by Django 5.1 on 2024-09-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("level_of_stuttering", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildModule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("duration", models.DurationField()),
                ("module_level", models.PositiveSmallIntegerField()),
                (
                    "level_of_stuttering_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_level_of_stuttering",
                        to="level_of_stuttering.levelofstuttering",
                    ),
                ),
            ],
        ),
    ]
