# Generated by Django 5.1 on 2024-09-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_module', '0001_initial'),
        ('level_of_stuttering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodule',
            name='level_of_stuttering_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_level_of_stuttering', to='level_of_stuttering.levelofstuttering'),
            preserve_default=False,
        ),
    ]
