# Generated by Django 5.1 on 2024-09-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_module', '0002_childmodule_level_of_stuttering_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
