# Generated by Django 5.1 on 2024-09-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_module', '0003_alter_childmodule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childmodule',
            old_name='level_of_stuttering_id',
            new_name='childprogress_level_of_stuttering_id',
        ),
    ]
