# Generated by Django 5.1 on 2024-09-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_module', '0004_rename_level_of_stuttering_id_childmodule_childprogress_level_of_stuttering_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childmodule',
            old_name='childprogress_level_of_stuttering_id',
            new_name='level_of_stuttering_id',
        ),
    ]
