# Generated by Django 5.1 on 2024-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_progress', '0002_childprogress_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprogress',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
