# Generated by Django 5.1 on 2024-09-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("level_of_stuttering", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildProgress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("started_module_at", models.DateField()),
                ("finished_module_at", models.DateField()),
                (
                    "current_level_of_stuttering_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="level_of_stuttering.levelofstuttering",
                    ),
                ),
            ],
        ),
    ]
