# Generated by Django 5.1.1 on 2024-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_management',
            name='gender',
            field=models.CharField(default='male', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child_management',
            name='middle_name',
            field=models.CharField(default='Mugume', max_length=28),
            preserve_default=False,
        ),
    ]
