# Generated by Django 5.1 on 2024-09-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0002_child_management_gender_child_management_middle_name'),
        ('level_of_stuttering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child_management',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='child_management',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='child_management',
            name='level_of_stuttering_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_module_level', to='level_of_stuttering.levelofstuttering'),
            preserve_default=False,
        ),
    ]
