# Generated by Django 5.1 on 2024-09-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0003_remove_child_management_gender_and_more'),
        ('child_module', '0003_alter_childmodule_id'),
        ('level_of_stuttering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_management',
            name='chiild_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='child_module_level', to='child_module.childmodule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child_management',
            name='gender',
            field=models.CharField(default='male', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child_management',
            name='middle_name',
            field=models.CharField(default='Nunda', max_length=28),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child_management',
            name='level_of_stuttering_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_management_level', to='level_of_stuttering.levelofstuttering'),
        ),
    ]
