# Generated by Django 5.1 on 2024-09-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0004_child_management_chiild_id_child_management_gender_and_more'),
        ('child_module', '0004_rename_level_of_stuttering_id_childmodule_childprogress_level_of_stuttering_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child_management',
            name='chiild_id',
        ),
        migrations.AddField(
            model_name='child_management',
            name='childmodule_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='child_management', to='child_module.childmodule'),
            preserve_default=False,
        ),
    ]
