# Generated by Django 5.1 on 2024-09-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0005_remove_child_management_chiild_id_and_more'),
        ('child_module', '0005_rename_childprogress_level_of_stuttering_id_childmodule_level_of_stuttering_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_management',
            name='childmodule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='child_module.childmodule'),
        ),
    ]
