# Generated by Django 4.2 on 2024-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech_therapist", "0002_speech_therapist_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speech_therapist",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
