# Generated by Django 4.2 on 2024-10-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speech_therapist", "0005_remove_speech_therapist_profile_picture_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speech_therapist",
            old_name="user_id",
            new_name="user",
        ),
    ]
